export const CREATE_WALLET = "CREATE_WALLET";
export const UPLOAD_PROFILE = "UPLOAD_PROFILE";
export const UPLOADED_PROFILE = "UPLOADED_PROFILE";
export const SAVE_CHANGES = "SAVE_CHANGES";
export const SAVE_CRYPTO_TEMPLATE_CHANGES = "SAVE_CRYPTO_TEMPLATE_CHANGES";
export const GET_WALLET = "GET_WALLET";

export const SEND_CRYPTO = "SEND_CRYPTO";
export const RECEIVE_CRYPTO = "RECEIVE_CRYPTO";
export const COPY_ADDRESS = "COPY_ADDRESS";

export const REGISTER_ACCOUNT = "REGISTER_ACCOUNT";
export const LOGIN_ACCOUNT = "LOGIN_ACCOUNT";
export const LOGOUT_ACCOUNT = "LOGOUT_ACCOUNT";
export const GET_ACCOUNT = "GET_ACCOUNT";
export const GOT_ACCOUNT = "GOT_ACCOUNT";
export const AUTHENTICATE = "AUTHENTICATE";

export const CHANGE_SELECTED_CRYPTO = "CHANGE_SELECTED_CRYPTO";
export const SIGN_TRANSACTION = "SIGN_TRANSACTION";
export const SET_RECIPIENT = "SET_RECIPIENT";
export const SET_AMOUNT_TO_SEND = "SET_AMOUNT_TO_SEND";

export const SET_CRYPTO_BALANCE = "SET_CRYPTO_BALANCE";
export const GET_CRYPTO_BALANCE = "GET_CRYPTO_BALANCE";

export const BALANCE_SYNC_START = "BALANCE_SYNC_START";
export const TRANSACTION_HISTORY_SYNC_START = "TRANSACTION_HISTORY_SYNC_START";

export const GOT_PROFILE = "GOT_PROFILE";
export const GOT_MNEMONIC = "GOT_MNEMONIC";
export const GOT_CREDENTIALS = "GOT_CREDENTIALS";
export const LOADED_CREDENTIALS = "LOADED_CREDENTIALS";

export const LOGIN_ACCOUNT_SUCCESS = "LOGIN_ACCOUNT_SUCCESS";
export const LOGIN_ACCOUNT_FAIL = "LOGIN_ACCOUNT_FAIL";

export const REGISTER_ACCOUNT_SUCCESS = "REGISTER_ACCOUNT_SUCCESS";
export const REGISTER_ACCOUNT_FAIL = "REGISTER_ACCOUNT_FAIL";

export const TRANSACTION_SIGNING_SUCCESS = "TRANSACTION_SIGNING_SUCCESS";
export const TRANSACTION_SIGNING_FAILED = "TRANSACTION_SIGNING_FAILED";

export const CLEAR_MESSAGES = "CLEAR_MESSAGES";

export const GET_TRANSACTION_HISTORY = "GET_TRANSACTION_HISTORY";
export const GOT_TRANSACTION_HISTORY = "GOT_TRANSACTION_HISTORY";

export const LOADING = "LOADING";
export const LOADED = "LOADED";

export const UPLOADING = "UPLOADING";
export const UPLOADED = "UPLOADED";

export const QR_LOGIN = "QR_LOGIN";
export const QR_LOGOUT = "QR_LOGOUT";
export const QR_TRANSACTION = "QR_TRANSACTION";

export const NAVIGATE = "NAVIGATE";


export const UPLOAD_FILE = "UPLOAD_FILE";
export const GET_FILES = "GET_FILES";
export const GOT_FILES = "GOT_FILES";

export const LOAD_APPLICATION = "LOAD_APPLICATION";
